# Generated by Django 6.0.4 on 2026-04-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monsters", "0001_initial"),
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KillStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_day_players_killed", models.IntegerField()),
                ("last_day_monsters_killed", models.IntegerField()),
                ("last_7_days_players_killed", models.IntegerField()),
                ("last_7_days_monsters_killed", models.IntegerField()),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monsters.monster",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snapshots.snapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "monster"),
                        name="unique_killstat_per_snapshot_monster",
                    )
                ],
            },
        ),
    ]
