# Generated by Django 6.0.4 on 2026-05-08 21:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monsters", "0001_initial"),
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonsterSpawnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="The exact moment the boss died or puffed.",
                        verbose_name="event timestamp",
                    ),
                ),
                (
                    "is_puff",
                    models.BooleanField(
                        default=False,
                        help_text="True if the boss despawned without being killed.",
                        verbose_name="is puff",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster spawn event",
                "verbose_name_plural": "monster spawn events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="KillStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_day_players_killed", models.IntegerField()),
                ("last_day_monsters_killed", models.IntegerField()),
                ("last_7_days_players_killed", models.IntegerField()),
                ("last_7_days_monsters_killed", models.IntegerField()),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kill_stats",
                        to="monsters.monster",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kill_stats",
                        to="snapshots.snapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "killstat",
                "verbose_name_plural": "killstats",
            },
        ),
        migrations.CreateModel(
            name="MonsterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The lower bound of the spawn window validated by a human.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="confirmed minimum interval",
                    ),
                ),
                (
                    "max_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The upper bound of the spawn window validated by an admin.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="confirmed maximum interval",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="validated at"
                    ),
                ),
                (
                    "monster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="monsters.monster",
                        verbose_name="monster",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster config",
                "verbose_name_plural": "monster configs",
            },
        ),
    ]
