# Generated by Django 6.0.4 on 2026-04-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Define se o monstro será exibido no monitor de bosses.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonsterMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum days for a new spawn.",
                        null=True,
                        verbose_name="minimum interval",
                    ),
                ),
                (
                    "max_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum days for a new spawn.",
                        null=True,
                        verbose_name="maximum interval",
                    ),
                ),
                (
                    "monster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="monsters.monster",
                        verbose_name="monster",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster metadata",
                "verbose_name_plural": "monster metadatas",
            },
        ),
    ]
