# Generated by Django 6.0.4 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Define se o monstro será exibido no monitor de bosses.",
                    ),
                ),
            ],
        ),
    ]
