# Generated by Django 6.0.4 on 2026-04-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="world",
            name="external_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
