# Generated by Django 6.0.4 on 2026-04-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monsters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMonsterPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pinned monsters appear at the top."
                    ),
                ),
                (
                    "is_low_priority",
                    models.BooleanField(
                        default=False,
                        help_text="Low priority monsters appear at the bottom.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="monsters.monster",
                    ),
                ),
            ],
            options={
                "verbose_name": "user monster preference",
                "verbose_name_plural": "user monster preferences",
            },
        ),
    ]
