# Generated by Django 6.0.4 on 2026-04-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monsters", "0001_initial"),
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KillStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_day_players_killed", models.IntegerField()),
                ("last_day_monsters_killed", models.IntegerField()),
                ("last_7_days_players_killed", models.IntegerField()),
                ("last_7_days_monsters_killed", models.IntegerField()),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kill_stats",
                        to="monsters.monster",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kill_stats",
                        to="snapshots.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonsterSpawnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="The exact moment the boss died or puffed.",
                        verbose_name="event timestamp",
                    ),
                ),
                (
                    "is_puff",
                    models.BooleanField(
                        default=False,
                        help_text="True if the boss despawned without being killed.",
                        verbose_name="is puff",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spawn_events",
                        to="monsters.monster",
                        verbose_name="monster",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster spawn event",
                "verbose_name_plural": "monster spawn events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
