# Generated by Django 6.0.4 on 2026-04-27 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("killstats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monsterspawnevent",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who manually reported this event via interface.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_spawn_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reported by",
            ),
        ),
        migrations.AddConstraint(
            model_name="killstat",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "monster"),
                name="unique_killstat_per_snapshot_monster",
            ),
        ),
    ]
