# Generated by Django 6.0.4 on 2026-04-27 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killstats", "0001_initial"),
        ("monsters", "0001_initial"),
        ("snapshots", "0002_alter_snapshot_snapshot_id_alter_snapshot_world_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="killstat",
            name="monster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kill_stats",
                to="monsters.monster",
            ),
        ),
        migrations.AlterField(
            model_name="killstat",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kill_stats",
                to="snapshots.snapshot",
            ),
        ),
    ]
