# Generated by Django 6.0.4 on 2026-04-27 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killstats", "0002_alter_killstat_monster_alter_killstat_snapshot"),
        ("monsters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonsterSpawnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="The exact moment the boss died or puffed.",
                        verbose_name="event timestamp",
                    ),
                ),
                (
                    "is_puff",
                    models.BooleanField(
                        default=False,
                        help_text="True if the boss despawned without being killed.",
                        verbose_name="is puff",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spawn_events",
                        to="monsters.monster",
                        verbose_name="monster",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who manually reported this event via interface.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_spawn_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reported by",
                    ),
                ),
            ],
            options={
                "verbose_name": "monster spawn event",
                "verbose_name_plural": "monster spawn events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
