# Generated by Django 6.0.4 on 2026-04-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("captured_at", models.DateTimeField()),
                ("source_file", models.CharField(max_length=255)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["captured_at"], name="snapshots_s_capture_85c176_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("world", "captured_at"),
                        name="unique_snapshot_per_world_datetime",
                    )
                ],
            },
        ),
    ]
