# Generated by Django 6.0.4 on 2026-04-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=100, unique=True)),
                ("captured_at", models.DateTimeField()),
                ("source_file", models.CharField(max_length=255)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worlds.world"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("world", "captured_at"),
                        name="unique_snapshot_per_world_datetime",
                    )
                ],
            },
        ),
    ]
