# Generated by Django 6.0.4 on 2026-04-27 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapshots", "0001_initial"),
        ("worlds", "0002_alter_world_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot",
            name="snapshot_id",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="worlds.world",
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["captured_at"], name="snapshots_s_capture_85c176_idx"
            ),
        ),
    ]
